# Generated by Django 5.0.3 on 2024-03-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['article'], 'verbose_name': 'продукция', 'verbose_name_plural': 'продукция'},
        ),
        migrations.AlterField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='артикул'),
        ),
        migrations.AlterField(
            model_name='good',
            name='color_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.colorscheme', verbose_name='цветовая схема'),
        ),
        migrations.AlterField(
            model_name='good',
            name='detail_quantity',
            field=models.SmallIntegerField(default=1, verbose_name='количество деталей'),
        ),
    ]
