# Generated by Django 5.0.3 on 2024-03-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0002_alter_good_options_alter_good_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=10, verbose_name='код'),
        ),
    ]
