# Generated by Django 5.0.3 on 2024-04-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0004_customer_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Тип детали',
                'verbose_name_plural': 'Типы деталей',
                'db_table': 'detail_types',
                'db_table_comment': 'Set of Detail Types',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='printplace',
            options={'ordering': ['name'], 'verbose_name': 'место нанесения (деталь)', 'verbose_name_plural': 'места нанесения (детали)'},
        ),
        migrations.AlterModelOptions(
            name='printposition',
            options={'ordering': ['name'], 'verbose_name': 'ориентация нанесения', 'verbose_name_plural': 'ориентации печати'},
        ),
        migrations.AddField(
            model_name='detailitem',
            name='detail_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.detailtype'),
        ),
    ]
