# Generated by Django 5.0.3 on 2024-04-07 20:22

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0006_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=18, null=True)),
                ('order_date', models.DateField(default='1000-01-01')),
                ('supplier', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inn', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('order_quantity', models.IntegerField(default=0)),
                ('order_sum', models.FloatField(default=0)),
                ('print_quantity', models.IntegerField(default=0)),
                ('print_sum', models.FloatField(default=0)),
                ('our_manager', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('maket_status', models.CharField(choices=[('R', 'R'), ('P', 'P'), ('N', 'N')], default='N', max_length=1)),
                ('order_upload', models.BooleanField(default=False)),
                ('order_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/orders'), upload_to='')),
                ('to_check', models.BooleanField(default=False)),
                ('number_orders', models.SmallIntegerField(default=0)),
                ('number_makets', models.SmallIntegerField(default=0)),
                ('number_additional', models.SmallIntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.customer')),
                ('manager', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.manager')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'db_table_comment': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_no', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('print_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_price', models.FloatField(default=0)),
                ('print_price', models.FloatField(default=0)),
                ('num_prints', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.good')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.order')),
            ],
            options={
                'verbose_name': 'Номенклатура заказа',
                'verbose_name_plural': 'Номенклатура завказов',
                'db_table': 'order_item',
                'db_table_comment': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='OrderPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('colors', models.SmallIntegerField(default=1)),
                ('second_pass', models.BooleanField(default=False)),
                ('print_no', models.IntegerField(default=0)),
                ('print_price', models.FloatField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.orderitem')),
                ('print_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.printplace')),
                ('print_position', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.printposition')),
            ],
            options={
                'verbose_name': 'Нанесение',
                'verbose_name_plural': 'Нанесения',
                'db_table': 'order_print',
                'db_table_comment': 'OrderPrint',
            },
        ),
        migrations.CreateModel(
            name='PrintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantone', models.CharField(default='', max_length=40)),
                ('hex', models.CharField(default='', max_length=7)),
                ('number_in_item', models.SmallIntegerField(default=1)),
                ('print_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket5_0.orderprint')),
            ],
            options={
                'verbose_name': 'Цвет нанесения',
                'verbose_name_plural': 'Цвета нанесения',
                'db_table': 'print_color',
                'db_table_comment': 'PrintColor',
            },
        ),
    ]
