# Generated by Django 5.0.4 on 2024-04-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0008_rename_address_order_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Номенклатура заказа', 'verbose_name_plural': 'Номенклатура заказов'},
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='телефон'),
        ),
    ]
