# Generated by Django 5.0.4 on 2024-04-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0009_alter_orderitem_options_alter_customergroup_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
