# Generated by Django 5.0.4 on 2024-04-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0011_orderprint_print_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printcolor',
            name='hex',
        ),
    ]
