# Generated by Django 5.0.4 on 2024-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0012_remove_printcolor_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='frigate_code',
            field=models.CharField(db_index=True, default='', max_length=30, verbose_name='фрегат id'),
        ),
    ]
