# Generated by Django 5.0.4 on 2024-04-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0013_alter_customer_frigate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('code', models.CharField(default='ВВ', max_length=4)),
            ],
            options={
                'verbose_name': 'продавец',
                'verbose_name_plural': 'продавцы',
                'db_table': 'our_companies',
                'db_table_comment': 'Our Companies',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='our_company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.ourcompany'),
        ),
    ]
