# Generated by Django 5.0.4 on 2024-04-22 18:44

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0014_ourcompany_order_our_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', '-order_number'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('additional_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='maket5_0/files/additional'), upload_to='')),
                ('additional_file_name', models.FilePathField(max_length=255)),
                ('file_type', models.CharField(blank=True, default='pdf', max_length=8, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket5_0.order')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'db_table': 'additional_file',
                'db_table_comment': 'AdditionalFile',
                'ordering': ['-order__order_date', 'order__order_number'],
                'abstract': False,
            },
        ),
    ]
