# Generated by Django 5.0.4 on 2024-04-27 05:21

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0015_alter_order_options_additionalfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='maket5_0/files/patterns'), upload_to='')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.good')),
            ],
            options={
                'verbose_name': 'шаблон нанесения',
                'verbose_name_plural': 'шаблоны нанесения',
                'db_table': 'patern',
                'db_table_comment': 'Pattern',
                'ordering': ['good__article'],
                'abstract': False,
            },
        ),
    ]
