# Generated by Django 5.0.4 on 2024-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0016_pattern'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pattern',
            table='pattern',
        ),
    ]
