# Generated by Django 5.0.4 on 2024-04-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0017_alter_pattern_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantoneToHex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('hex', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'pantone_to_hex',
                'verbose_name_plural': 'pantone_to_hex',
                'db_table': 'pantone_to_hex',
                'db_table_comment': 'PantoneToHex',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.order'),
        ),
        migrations.AlterField(
            model_name='orderprint',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.orderitem'),
        ),
    ]
