# Generated by Django 5.0.4 on 2024-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0019_film_maket_maketitem_iteminfilm_maketprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maket',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
