# Generated by Django 5.0.4 on 2024-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0020_alter_maket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
