# Generated by Django 5.0.4 on 2024-05-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0021_orderitem_item_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailitem',
            name='detail_images_set',
        ),
        migrations.RemoveField(
            model_name='detailitem',
            name='detail_type',
        ),
        migrations.RemoveField(
            model_name='detailitem',
            name='good',
        ),
        migrations.RemoveField(
            model_name='detailitem',
            name='material_type',
        ),
        migrations.DeleteModel(
            name='DetailType',
        ),
        migrations.DeleteModel(
            name='DetailItem',
        ),
    ]
