# Generated by Django 5.0.4 on 2024-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0022_remove_detailitem_detail_images_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaketPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'шаблон представления в макете',
                'verbose_name_plural': 'шаблоны представления в макете',
                'db_table': 'maket_pattern',
                'db_table_comment': 'МакетPattern',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
