# Generated by Django 5.0.4 on 2024-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0023_maketpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='maketpattern',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
