# Generated by Django 5.0.4 on 2024-05-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0025_good_maket_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailimage',
            name='detail_image_set',
        ),
        migrations.AlterModelOptions(
            name='detailimage',
            options={'ordering': ['goods_image_set', 'image_number'], 'verbose_name': 'SVG код элемента', 'verbose_name_plural': 'SVG код элементов'},
        ),
        migrations.CreateModel(
            name='GoodsImagesSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('images_quantity', models.IntegerField(verbose_name='количество изображений элемента')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.good')),
            ],
            options={
                'verbose_name': 'Набор изображений изделия',
                'verbose_name_plural': 'Наборы изображений изделий',
                'db_table': 'goods_images_set',
                'db_table_comment': 'Set of Goods Images',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detailimage',
            name='goods_image_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.goodsimagesset', verbose_name='набор изображений'),
        ),
        migrations.DeleteModel(
            name='DetailImagesSet',
        ),
    ]
