# Generated by Django 5.0.4 on 2024-05-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0026_remove_detailimage_detail_image_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimagesset',
            name='good',
        ),
    ]
