# Generated by Django 5.0.4 on 2024-05-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0027_remove_goodsimagesset_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='goods_images_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.goodsimagesset', verbose_name='набор шаблонов'),
        ),
    ]
