# Generated by Django 5.0.4 on 2024-05-09 14:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0029_printtype_printable'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailimage',
            name='image_width',
            field=models.FloatField(blank=True, default=138.205, null=True),
        ),
        migrations.AlterField(
            model_name='detailimage',
            name='svg_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='maket5_0/files/detail_images'), upload_to='', verbose_name='файл изображения'),
        ),
    ]
