# Generated by Django 5.0.4 on 2024-05-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0030_detailimage_image_width_alter_detailimage_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPlaceToPrintPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('print_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket5_0.printplace')),
                ('print_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket5_0.printposition')),
            ],
            options={
                'verbose_name': 'соответствие места и ориентации нанесения',
                'verbose_name_plural': 'соответствие места и ориентации нанесения',
                'db_table': 'print_place_to_print_position',
                'db_table_comment': 'Print Place to Print Position',
                'ordering': ['print_place__name'],
                'abstract': False,
            },
        ),
    ]
