# Generated by Django 5.0.4 on 2024-05-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0031_printplacetoprintposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maket',
            options={'ordering': ['-order__order_number', 'maket_number'], 'verbose_name': 'макет', 'verbose_name_plural': 'макеты'},
        ),
        migrations.RenameField(
            model_name='maketitem',
            old_name='checked',
            new_name='in_maket',
        ),
        migrations.RemoveField(
            model_name='maket',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='maket',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='maketitem',
            name='print_name',
        ),
        migrations.AddField(
            model_name='maket',
            name='before_footer',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maket',
            name='format_selected',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='maket',
            name='frame_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maket',
            name='picture_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maket',
            name='table_show',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MaketGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show', models.BooleanField(default=True)),
                ('select_all', models.BooleanField(default=False)),
                ('show_miniature', models.BooleanField(default=True)),
                ('spaces_before', models.SmallIntegerField(default=0)),
                ('maket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket5_0.maket')),
            ],
            options={
                'verbose_name': 'группировка в макете',
                'verbose_name_plural': 'группировки в макетах',
                'db_table': 'maket_group',
                'db_table_comment': 'MaketGroup',
            },
        ),
    ]
