# Generated by Django 5.0.4 on 2024-05-20 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0032_alter_maket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maketprint',
            name='print_place',
        ),
        migrations.RemoveField(
            model_name='maketprint',
            name='print_position',
        ),
        migrations.RemoveField(
            model_name='maketprint',
            name='print_type',
        ),
    ]
