# Generated by Django 5.0.4 on 2024-06-01 17:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0033_remove_maketprint_print_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_upload',
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='GroupInFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.film')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.maketgroup')),
            ],
            options={
                'verbose_name': 'нанесение на пленке',
                'verbose_name_plural': 'нанесения на пленках',
                'db_table': 'group-in-film',
                'db_table_comment': 'GroupInFilm',
                'ordering': ['-film__date', '-film__film_number', 'group__name'],
            },
        ),
    ]
