# Generated by Django 5.0.4 on 2024-06-09 05:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0036_groupinfilm_deleted_alter_film_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='if_print',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='maket5_0/files/film'), upload_to=''),
        ),
    ]
