# Generated by Django 5.0.4 on 2024-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0037_orderitem_if_print_alter_film_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalfile',
            old_name='additional_file',
            new_name='file',
        ),
    ]
