# Generated by Django 5.0.4 on 2024-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0039_z_color_scheme_z_customer_groups_z_customer_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_additional_files',
            name='file_type',
            field=models.CharField(blank=True, default='pdf', max_length=4, null=True),
        ),
    ]
