# Generated by Django 5.0.4 on 2024-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0040_alter_z_additional_files_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_additional_files',
            name='file_type',
            field=models.CharField(blank=True, default='pdf', max_length=3, null=True),
        ),
    ]
