# Generated by Django 5.0.4 on 2024-10-15 09:47

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket5_0', '0041_alter_z_additional_files_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_Makety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(blank=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('maket_id', models.SmallIntegerField(default=0)),
                ('uploaded', models.BooleanField(default=False)),
                ('maket_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files_m/makety'), upload_to='')),
                ('comment', models.CharField(default='', max_length=255)),
                ('order_num', models.CharField(blank=True, max_length=18, null=True)),
                ('order_date', models.DateField(default='1000-01-01')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.z_order_imports')),
            ],
        ),
        migrations.CreateModel(
            name='Z_Itemgroup_in_Maket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=True)),
                ('print_name', models.CharField(blank=True, max_length=50, null=True)),
                ('film_error', models.BooleanField(default=True)),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.z_films')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.z_item_imports')),
                ('maket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.z_makety')),
            ],
        ),
        migrations.CreateModel(
            name='Z_Print_in_Maket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=True)),
                ('option', models.SmallIntegerField(default=1)),
                ('maket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket5_0.z_makety')),
                ('print_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket5_0.z_print_imports')),
            ],
        ),
    ]
