from maket5_0.views.login import *
from maket5_0.views.dictionary_settings import *
from maket5_0.views.dictionary_data import *
from maket5_0.views.file_import import *
from maket5_0.views.import_order import *
from maket5_0.views.order import *
from maket5_0.views.additional_files import *
from maket5_0.views.pattern import *
from maket5_0.views.files import *
from maket5_0.views.maket import *
